[project]
name = "curlipie"
description = "Library to convert cURL command line to HTTPie"
authors = [{ name = "Nguyễn Hồng Quân", email = "ng.hong.quan@gmail.com" }]
maintainers = [{ name = "Nguyễn Hồng Quân", email = "ng.hong.quan@gmail.com" }]
dynamic = ["version"]
readme = "README.rst"
license = { text = "MPL-2.0" }
requires-python = "<4.0,>=3.14"
dependencies = [
  "first>=2.0.2",
  "http-constants>=0.5.0",
  "kiss-headers>=2.5.0",
  "logbook>=1.10.1",
  "multidict>=6.8.0",
  "orjson>=3.12.0",
  "pydantic>=2.13.5",
  "pydantic-settings>=2.15.0",
  "typed-argument-parser>=1.12.0",
  "yarl>=1.24.5",
]
classifiers = [
  "Environment :: Web Environment",
  "Intended Audience :: Developers",
  "Intended Audience :: System Administrators",
  "Topic :: Internet :: WWW/HTTP",
  "Topic :: Software Development :: Libraries :: Python Modules",
]
keywords = ["api", "cli", "conversion", "curl", "http", "httpie"]

[project.scripts]
curlipie = "curlipie.cli:main"

[project.urls]
repository = "https://github.com/hongquan/CurliPie.git"

[dependency-groups]
dev = [
  "aiofiles>=25.1.0",
  "devtools>=0.12.2",
  "fastapi>=0.141.1",
  "jinja2>=3.1.6",
  "uvicorn>=0.52.4",
]
lint = [
  "ruff>=0.16.7",
]
test = [
  "mypy>=2.3.1",
  "pytest-mypy>=1.0.1",
  "types-first>=2.0.5.20260408",
]

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.mypy]
python_version = "3.12"
allow_redefinition = true
plugins = [
  "pydantic.mypy",
]
# These options are recommended by Pydantic.
follow_imports = "silent"
warn_redundant_casts = true
warn_unused_ignores = true
disallow_any_generics = true

[[tool.mypy.overrides]]
module = [
  "devtools.*",
  "logbook.*",
  "http_constants.headers.*",
]
ignore_missing_imports = true

[tool.pydantic-mypy]
init_typed = true
init_forbid_extra = true
warn_required_dynamic_aliases = true

[tool.pytest.ini_options]
addopts = "--mypy"
minversion = "8.0"
testpaths = ["tests", "curlipie"]

[tool.ruff]
line-length = 120
# Exclude a variety of commonly ignored directories.
exclude = [
  ".bzr",
  ".direnv",
  ".eggs",
  ".git",
  ".hg",
  ".mypy_cache",
  ".nox",
  ".pants.d",
  ".ruff_cache",
  ".svn",
  ".tox",
  ".venv",
  "__pypackages__",
  "_build",
  "buck-out",
  "build",
  "dist",
  "node_modules",
  "venv",
]
target-version = "py312"

[tool.ruff.lint]
# Enable Pyflakes `E` and `F` codes by default.
select = ["E", "F"]
ignore = []
# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.format]
quote-style = "single"
