name: Run test

on: push

jobs:
  matrix-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.11", "3.10", "3.9", "3.8"]
    steps:
      - uses: actions/checkout@v4
      - name: ASDF Parse
        uses: kota65535/github-asdf-parse-action@v1.1.0
        id: versions
      - uses: actions/setup-python@v5
        with:
          python-version: "${{ matrix.python-version }}"
      - uses: abatilo/actions-poetry@v3.0.0
        with:
          poetry-version: 1.7.1
      - run: poetry install --no-root
      - run: poetry run pytest
