name: Run test

on: push

jobs:
  matrix-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12",]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "${{ matrix.python-version }}"
      - uses: abatilo/actions-poetry@v3.0.0
        with:
          poetry-version: 1.8.3
      - run: poetry install --no-root
      - run: poetry run pytest
